targets:
  - type: cert
    port: 443
    addresses:
      - vc-01.vcf-lab.local
      - ops-01.vcf-lab.local
      - auto-01.vcf-lab.local
    timeout: 10
  - type: icmp
    vms:
      parentType: "cluster"
      parentName: "vcf-lab-mgmt"
      includeIps:
        - 192.168.1.0/24
      excludeIps:
        - 192.168.2.0/24
    addresses:
      - vc-01.vcf-lab.local
      - ops-01.vcf-lab.local
      - auto-01.vcf-lab.local
      - google.com
    timeout: 10

  - type: tcp
    port: 443
    addresses:
      - vc-01.vcf-lab.local
      - ops-01.vcf-lab.local
      - auto-01.vcf-lab.local
    timeout: 10

  - type: url
    addresses:
      - https://vc-01.vcf-lab.local
      - https://ops-01.vcf-lab.local
      - https://auto-01.vcf-lab.local
      - https://vmware.com/foobar
    timeout: 10
  - type: cert
    port: 443
    vms:
      parentType: "cluster"
      parentName: "vcf-lab-mgmt"
      includeIps:
        - 192.168.1.0/24
      excludeIps:
        - 192.168.2.0/24
    addresses:
      - www.google.com
      - broadcom.com
      - whitehouse.gov
      - www.vmware.com
    timeout: 10

